### ISSUE TITLE
Error when environment installing Drupal

### ISSUE THREAD

**Issue by vacho** [docksal/drupal9-contrib#4]
After fin init...

Installing Drupal...
Unable to load class Drush\Sql\Sql                                                                                                                                                                                                 [error]
Drush\Sql\SqlException: Unable to find a matching SQL Class. Drush cannot find your database connection details. in phar:///usr/local/bin/drush8/commands/sql/sql.drush.inc:554                                                    [error]
Stack trace:
#0 phar:///usr/local/bin/drush8/commands/core/site_install.drush.inc(124): drush_sql_get_class()
#1 phar:///usr/local/bin/drush8/includes/command.inc(422): drush_core_pre_site_install('standard', 'install_configu...')
#2 phar:///usr/local/bin/drush8/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#3 phar:///usr/local/bin/drush8/includes/command.inc(199): drush_command('standard', 'install_configu...')
#4 phar:///usr/local/bin/drush8/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#5 phar:///usr/local/bin/drush8/includes/preflight.inc(67): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#6 phar:///usr/local/bin/drush8/includes/startup.inc(465): drush_main()
#7 phar:///usr/local/bin/drush8/includes/startup.inc(369): drush_run_main(false, '/', 'Phar detected. ...')
#8 phar:///usr/local/bin/drush8/drush(114): drush_startup(Array)
#9 /usr/local/bin/drush8(10): require('phar:///usr/loc...')
#10 {main}
real 0.25
user 0.21
sys 0.04

**Comment by jhedstrom** [comment]
Hmm, could you try editing `.docksal/commands/init-site` to add `--verbose` to the various drush commands run within there?

**Comment by vacho** [comment]
After add --verbose to command  `drush site-install --verbose standard -y \` 

Same message, no more details
Installing Drupal...
Unable to load class Drush\Sql\Sql                                                                                                                                                                                                 [error]
Drush\Sql\SqlException: Unable to find a matching SQL Class. Drush cannot find your database connection details. in phar:///usr/local/bin/drush8/commands/sql/sql.drush.inc:554                                                    [error]
Stack trace:
#0 phar:///usr/local/bin/drush8/commands/core/site_install.drush.inc(124): drush_sql_get_class()
#1 phar:///usr/local/bin/drush8/includes/command.inc(422): drush_core_pre_site_install('standard', 'install_configu...')
#2 phar:///usr/local/bin/drush8/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#3 phar:///usr/local/bin/drush8/includes/command.inc(199): drush_command('standard', 'install_configu...')
#4 phar:///usr/local/bin/drush8/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#5 phar:///usr/local/bin/drush8/includes/preflight.inc(67): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#6 phar:///usr/local/bin/drush8/includes/startup.inc(465): drush_main()
#7 phar:///usr/local/bin/drush8/includes/startup.inc(369): drush_run_main(false, '/', 'Phar detected. ...')
#8 phar:///usr/local/bin/drush8/drush(114): drush_startup(Array)
#9 /usr/local/bin/drush8(10): require('phar:///usr/loc...')
#10 {main}
Command dispatch complete                                                                                                                                                                                                             [notice]
real 0.24
user 0.19
sys 0.04

**Comment by jhedstrom** [comment]
Can you run `fin config show | grep image` and paste the results here? (alternatively the entire output of `fin config show` would be useful too.)
